[package]
name = "link-mailer"
version = "0.1.0"
authors = ["Alan Malloy <alan.j.malloy@protonmail.com>"]

[dependencies]
web-view = "0.2.1"
serde_json = "1.0.19"
serde_derive = "1.0.64"
serde = "1.0.64"
open = "1.2.1"
url = "1.7.0"
calamine = "0.14.1"
failure = "0.1.1"
strsim = "0.7.0"
